name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: cd
      run: cd SiteMapGeneratorTool/SiteMapGeneratorTool/SiteMapGeneratorTool
    - name: ls
      run: ls
    - name: Decrypt Secret
      run: ./SiteMapGeneratorTool/SiteMapGeneratorTool/SiteMapGeneratorTool/decrypt.sh
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.APP_SETTINGS_PASSWORD }}
    - name: Build
      run: dotnet build SiteMapGeneratorTool
    - name: Unit Test
      run: dotnet test --no-build --verbosity normal SiteMapGeneratorTool/SiteMapGeneratorToolTests
    - name: Selenium Test
      run: dotnet test --no-build --verbosity normal SiteMapGeneratorTool/SiteMapGeneratorToolSelenium
